name: UpdayNodePipeline
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
jobs:
  deploy-job:
    name: Deployment
    uses: upday/gha-shared-workflow/.github/workflows/NodePipeline.yml@SRE-1275
    with:
      project: upday
      node_version: 16.16.0
      data_location: storybook-static
      s3_staging_bucket_name: upday-react-ui-components-staging.upday.com
      s3_prod_bucket_name: upday-react-ui-components-prod.upday.com
      skip_terraform: false
    secrets:
      git_token: ${{ secrets.PAT_GIT }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      deployment_notification_webhook: ${{ secrets.DEPLOYMENT_NOTIFICATION_WEBHOOK }}