name: UpdayNodePipeline
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
jobs:
  deploy-job:
    name: Deployment
    uses: 
    with:
      project: upday
      node_version: 16.16.0
      data_location: 
      s3_staging_bucket_name: 
      s3_prod_bucket_name: 
      skip_terraform: false
    secrets:
      git_token: 
      docker_username:
      docker_password:
      deployment_notification_webhook: 