name: Pull Request Workflow

on:
  pull_request:
    branches:
      - staging
      - main  # Replace with the branch you want to target

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Replace with the Node.js version you need

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
