name: Vue Library CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          cd capstone/upday-vue-library
          npm install

      - name: Build and Test
        run: |
          cd capstone/upday-vue-library
          npm run build

